### ISSUE TITLE
NPM run build issue

### ISSUE THREAD

**Issue by Sumo99** [phylogeny-explorer/explorer#122]
**Describe the bug**
npm run start does not work on my system due to several errors. 
    Module build failed: Error: This API has been removed. If you're looking for this functionality in Babel 7, you should import the '@babel/helper-module-imports' module and use the functions exposed  from that module, such as 'addNamed' or 'addDefault'.

**To Reproduce**
Run npm start after npm build.
**Expected behavior**

**Screenshots**
Output from npm start is attached.
**Desktop (please complete the following information):**
This was built on Ubuntu 18.04.
**Smartphone (please complete the following information):**

**Additional context**
[error.txt](https://github.com/phylogeny-explorer/explorer/files/3351128/error.txt)
Here is the output from npm run start.

**Comment by orwell1984** [comment]
The project is being run via `npx pm2 start ecosystem.config.js` command.

Check out our wiki to see how to build and run the project - https://github.com/phylogeny-explorer/explorer/wiki/Getting-Started-with-Development
